version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: hr_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hr_management
      MYSQL_USER: hr_user
      MYSQL_PASSWORD: hr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicación HR API
  hr-api:
    build: .
    container_name: hr_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hr_management?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: hr_user
      SPRING_DATASOURCE_PASSWORD: hr_password
      JWT_SECRET: mi_clave_secreta_muy_segura_para_jwt_tokens_2025
      JWT_EXPIRATION: 86400000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Adminer para gestión de base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: hr_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - hr_network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  hr_network:
    driver: bridge
